### ISSUE TITLE
combination of ctrl+alt+key does not work

### ISSUE THREAD

**Issue by der-ali** [Jon-Salmon/hotkey-tabs#3]
when assigning a shortcut with the combination of ctrl+alt+key the field will reset it to alt+key.

I am using firefox 60 on Linux Mint 18.3 Sylvia

**Comment by Jon-Salmon** [comment]
I'm afraid the webextention implementation of command keys only supports `shift` as a secondary modifier key, hence the `ctrl+alt+...` combination cannot be used. 

Check this article out for more details if your interested https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands

**Comment by Jon-Salmon** [comment]
There is actually a bugzilla card open for this to be implemented (https://bugzilla.mozilla.org/show_bug.cgi?id=1426958), which was approved in Janurary. It's just a case of waiting for somebody to implement it now!
